project_id = "slxvlocunadfcwzptpqd"

[functions.generate-diagnosis]
verify_jwt = false

[functions.get-pipedrive-deal]
verify_jwt = false

[functions.update-pipedrive-deal]
verify_jwt = false

[functions.find-deal-by-email]
verify_jwt = false